version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: America/Chicago
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@octokit/types"
    versions:
    - 6.10.0
    - 6.10.1
    - 6.11.1
    - 6.11.2
    - 6.12.0
    - 6.12.1
    - 6.12.2
    - 6.13.0
    - 6.13.1
    - 6.13.2
    - 6.14.0
    - 6.6.0
    - 6.7.0
    - 6.7.1
    - 6.8.3
    - 6.8.5
    - 6.9.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: fp-ts
    versions:
    - 2.10.0
    - 2.10.1
    - 2.10.4
    - 2.9.3
    - 2.9.5
  - dependency-name: "@octokit/rest"
    versions:
    - 18.0.15
    - 18.1.0
    - 18.1.1
    - 18.2.0
    - 18.2.1
    - 18.3.0
    - 18.3.1
    - 18.3.2
    - 18.3.3
    - 18.3.4
    - 18.3.5
    - 18.4.0
    - 18.5.0
    - 18.5.2
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: io-ts
    versions:
    - 2.2.13
    - 2.2.14
    - 2.2.15
    - 2.2.16
  - dependency-name: "@stoplight/spectral"
    versions:
    - 5.8.0
    - 5.8.1
    - 5.9.0
    - 5.9.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: urijs
    versions:
    - 1.19.5
    - 1.19.6
  - dependency-name: "@octokit/graphql"
    versions:
    - 4.5.9
    - 4.6.0
  - dependency-name: "@octokit/request"
    versions:
    - 5.4.13
    - 5.4.14
  - dependency-name: "@types/lodash"
    versions:
    - 4.14.168
  - dependency-name: fast-glob
    versions:
    - 3.2.5
  - dependency-name: "@types/urijs"
    versions:
    - 1.19.14
  - dependency-name: tslib
    versions:
    - 2.1.0
  - dependency-name: prettier
    versions:
    - 2.2.1
  registries:
  - npm-registry-registry-npmjs-org
